owlv2:
  model: "google/owlv2-base-patch16-ensemble"
  threshold: 0.15

sam:
  model_type: "vit_h"
  checkpoint_path: "https://drive.google.com/file/d/1-pOLBMTX8LI2go8eYC_X-9OC_YDKKjoB/view?usp=drive_link"

mask_processing:
  expand_pixels: 10
  blur_radius: 25
  mask_threshold: 127

device: "cuda"  # or "cpu"