sam:
  model_type: "vit_h"
  checkpoint_path: "models/sam_vit_h_4b8939.pth"

mask_processing:
  expand_pixels: 10
  blur_radius: 25
  mask_threshold: 127
  dilation_proportion: 0.015

device: "cuda"  # or "cpu"