mi_gan:
  model_path: "models/migan_512_places2.pt"
  parameters:
    expand_pixels: 50
    dilation_iterations: 2
    detection_threshold: 0.2
  temp_dirs:
    input: "test_image/images"
    mask: "test_image/masks"
    output: "test_image/results"